ERROR - 2023-03-29 11:39:56 --> mysqli_sql_exception: Unknown column 'nik' in 'field list' in C:\xampp\htdocs\hcm-infomedia\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\hcm-infomedia\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `ev...', 0)
#1 C:\xampp\htdocs\hcm-infomedia\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ev...')
#2 C:\xampp\htdocs\hcm-infomedia\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ev...')
#3 C:\xampp\htdocs\hcm-infomedia\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ev...', Array, false)
#4 C:\xampp\htdocs\hcm-infomedia\vendor\codeigniter4\framework\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\hcm-infomedia\vendor\codeigniter4\framework\system\BaseModel.php(748): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\hcm-infomedia\vendor\codeigniter4\framework\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\hcm-infomedia\app\Models\DataDocReward.php(33): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\hcm-infomedia\app\Controllers\EventController.php(868): App\Models\DataDocReward->insertData(Array)
#9 C:\xampp\htdocs\hcm-infomedia\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\EventController->successsendingreward('123456181795')
#10 C:\xampp\htdocs\hcm-infomedia\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EventController))
#11 C:\xampp\htdocs\hcm-infomedia\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\hcm-infomedia\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\hcm-infomedia\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-03-29 11:39:56 --> Unknown column 'nik' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `event` (`id`, `nik`, `claim_id`, `reward_id`, `created_at`, `updated_at`) VALUES (\'12345618179503292023113956\', \'181795\', \'123456181795\', \'123456\', \'2023-03-29 11:39:56\', \'2023-03-29 11:39:56\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `event` (`id`, `nik`, `claim_id`, `reward_id`, `created_at`, `updated_at`) VALUES (\'12345618179503292023113956\', \'181795\', \'123456181795\', \'123456\', \'2023-03-29 11:39:56\', \'2023-03-29 11:39:56\')')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `event` (`id`, `nik`, `claim_id`, `reward_id`, `created_at`, `updated_at`) VALUES (\'12345618179503292023113956\', \'181795\', \'123456181795\', \'123456\', \'2023-03-29 11:39:56\', \'2023-03-29 11:39:56\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `event` (`id`, `nik`, `claim_id`, `reward_id`, `created_at`, `updated_at`) VALUES (:id:, :nik:, :claim_id:, :reward_id:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(748): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\DataDocReward.php(33): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\EventController.php(868): App\Models\DataDocReward->insertData([...])
10 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\EventController->successsendingreward('123456181795')
11 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EventController))
12 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2023-03-29 11:50:55 --> mysqli_sql_exception: Unknown column 'reward_id' in 'field list' in C:\xampp\htdocs\hcm-infomedia\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\hcm-infomedia\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `do...', 0)
#1 C:\xampp\htdocs\hcm-infomedia\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `do...')
#2 C:\xampp\htdocs\hcm-infomedia\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `do...')
#3 C:\xampp\htdocs\hcm-infomedia\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `do...', Array, false)
#4 C:\xampp\htdocs\hcm-infomedia\vendor\codeigniter4\framework\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\hcm-infomedia\vendor\codeigniter4\framework\system\BaseModel.php(748): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\hcm-infomedia\vendor\codeigniter4\framework\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\hcm-infomedia\app\Models\DataDocReward.php(33): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\hcm-infomedia\app\Controllers\EventController.php(868): App\Models\DataDocReward->insertData(Array)
#9 C:\xampp\htdocs\hcm-infomedia\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\EventController->successsendingreward('123456181795')
#10 C:\xampp\htdocs\hcm-infomedia\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EventController))
#11 C:\xampp\htdocs\hcm-infomedia\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\hcm-infomedia\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\hcm-infomedia\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-03-29 11:50:55 --> Unknown column 'reward_id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `doc_reward` (`id`, `nik`, `claim_id`, `reward_id`, `created_at`, `updated_at`) VALUES (\'12345618179503292023115055\', \'181795\', \'123456181795\', \'123456\', \'2023-03-29 11:50:55\', \'2023-03-29 11:50:55\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `doc_reward` (`id`, `nik`, `claim_id`, `reward_id`, `created_at`, `updated_at`) VALUES (\'12345618179503292023115055\', \'181795\', \'123456181795\', \'123456\', \'2023-03-29 11:50:55\', \'2023-03-29 11:50:55\')')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `doc_reward` (`id`, `nik`, `claim_id`, `reward_id`, `created_at`, `updated_at`) VALUES (\'12345618179503292023115055\', \'181795\', \'123456181795\', \'123456\', \'2023-03-29 11:50:55\', \'2023-03-29 11:50:55\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `doc_reward` (`id`, `nik`, `claim_id`, `reward_id`, `created_at`, `updated_at`) VALUES (:id:, :nik:, :claim_id:, :reward_id:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(748): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\DataDocReward.php(33): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\EventController.php(868): App\Models\DataDocReward->insertData([...])
10 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\EventController->successsendingreward('123456181795')
11 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EventController))
12 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-29 12:10:23 --> Invalid file: newhomepage.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('newhomepage.php')
 2 SYSTEMPATH\Common.php(1142): CodeIgniter\View\View->render('newhomepage', [], true)
 3 APPPATH\Controllers\Home.php(20): view('newhomepage')
 4 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Home->homepage()
 5 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
